Update Architecture
clouditor/clouditor pull request #319
Opened 2021-09-10 08:38 UTC by lebogg

2021-09-17 20:55 UTC, lebogg commented
Current state:
- discovery now without standalone functionality (remove the _if_ part)
- Changed namings and some request/response types in the .proto files, e.g. more booleans as response messages for giving information if a method was successful.
- Also changed ordering of within .proto files according to Google API conventions (see Readme in proto folder)
- Moved  go:generate commands for services to proto/compile_proto_files.go
- Added evidence store with methods: storeEvidence(s) and listEvidences. Evidences stored in memory
- Commented out tests for standalone discovery
- Added tests for discovery service
- Added tests for evidence store
- I didn't write unit tests for gRPC connections. I am not sure if that it is necessary (I guess we don't test if gRPC technology per se). The tests check if the output of implemented gRPC calls is good.

ToDo:
- @oxisto there are two anti-patterns in cmd/engine/engine.go (not marked as such in the main branch although they are the same)
- In TestGetMetric (cli/commands/metric/metric_test.go) I had to comment the last part out. I didn't understand what that unmarshal part was for. And how it should work with the new _metric_-ony response type (instead of _getMetricResponse_).

2021-09-19 08:04 UTC, oxisto requested changes

2021-09-19 08:04 UTC, oxisto commented on service/orchestrator/orchestrator.go
> +// Metrics
```suggestion
// LoadMetrics loads metrics definitions from a JSON file.
```

2021-09-19 08:04 UTC, oxisto commented on service/standalone/assessment.go
>  package standalone
Is this package obsolete now?

2021-09-22 10:11 UTC, garuppel commented on cmd/engine/engine.go
> +var evidenceStoreService evidenceStore.EvidenceStoreServer
We should name it evidenceService, since it does more than store evidences, e.g., ListEvidences.

2021-09-23 09:25 UTC, garuppel commented on service/assessment/assessment.go
> +		evidenceRequest := &assessment.AssessEvidenceRequest{
Fixed

2021-09-23 09:29 UTC, garuppel commented on service/assessment/assessment.go
> +func (s Service) handleEvidence(evidence *assessment.AssessEvidenceRequest) (result *assessment.AssessEvidenceResponse, err error) {
Fixed

2021-09-23 11:37 UTC, garuppel commented on service/assessment/assessment.go
> +	result = &assessment.AssessEvidenceResponse{
I seem to remember that we wanted to return a bool here. I have changed it accordingly. @oxisto Please check.

2021-09-24 07:12 UTC, garuppel commented
According to [Link](https://go.dev/blog/package-names) the package names shouldn´t be in camelCase or snake_Case. "When renaming an imported package, the local name should follow the same guidelines as package names (lower case, no under_scores or mixedCaps)."
Do we want to follow that?

2021-09-24 07:23 UTC, garuppel commented on proto/evidence_store.proto
> +option go_package = "api/evidenceStore";
According to Link the package names shouldn´t be in camelCase or snake_Case. "When renaming an imported package, the local name should follow the same guidelines as package names (lower case, no under_scores or mixedCaps)."
Do we want to follow that?

2021-09-24 07:30 UTC, garuppel commented on proto/orchestrator.proto
> +  // Obsolete: Stores stream of evidences. This responsibility is shifted now to the evidence store component.
Removed.

2021-09-24 07:48 UTC, garuppel commented on proto/orchestrator.proto
> +  rpc StreamAssessmentResults(stream AssessmentResult) returns (google.protobuf.Empty);
Done

2021-09-27 11:58 UTC, garuppel commented on cmd/engine/engine.go
> +	"clouditor.io/clouditor/api/evidence_store"
According to [Link](https://golang.org/doc/effective_go#package-names) the package names shouldn´t be in camelCase or snake_case.

2021-09-27 12:03 UTC, garuppel commented on proto/Readme.md
> +
It´s missing if we always use response/request messages or only if >1 return values are present.

2021-09-27 12:09 UTC, garuppel commented on proto/assessment.proto
> +message TriggerAssessmentRequest { string someOption = 1; }
If it is a custom method, than it needs also a response message.

2021-09-27 12:13 UTC, garuppel commented on proto/evidence_store.proto
> +  rpc StoreEvidence(Evidence) returns (StoreEvidenceResponse);
If it is a custom method, I think it need also a response message.

2021-09-27 12:14 UTC, garuppel commented on proto/orchestrator.proto
>        returns (AssessmentTool) {
RegisterAssessmentToolResponse?

2021-09-27 12:20 UTC, garuppel commented on proto/orchestrator.proto
>        returns (google.protobuf.Empty) {
Why is the response emtpy? Shouldn't that return something (succeed/error)?

2021-09-27 12:33 UTC, garuppel reviewed
Review finished.

2021-09-29 07:10 UTC, garuppel commented on proto/Readme.md
> +
I´ve updated the Readme.

2021-09-29 08:52 UTC, oxisto approved these changes

2021-09-29 08:53 UTC, merged